version: "3.8"

services:
  collector:
    build: collector
    volumes:
      - collectd:/var/lib/collectd

  monitor:
    build: monitor
    volumes:
      - collectd:/var/lib/collectd:ro

volumes:
  collectd:
