version: "3.8"

services:
  collector:
    build: collector
    volumes:
      - collectd:/var/lib/collectd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # entrypoint: sh -c 'while true; do sleep 60; done'

  monitor:
    build: monitor
    volumes:
      - collectd:/var/lib/collectd:ro

volumes:
  collectd:
